org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mod_id=minigame
mod_name=Minigame Mod
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.minigame
mod_authors=Minigame
mod_description=A minigame mod for Minecraft Fabric 1.20.1

minecraft_version=1.20.1
yarn_mappings=1.20.1+build.2
loader_version=0.14.21
fabric_version=0.88.1+1.20.1
